server {
    listen 8080;
    server_name localhost;

    # Opciones de seguridad básicas
    server_tokens off;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Necesario para React Router (Single Page Application)
        try_files $uri $uri/ /index.html;
    }

    # Caché para recursos estáticos para optimizar el rendimiento
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Manejo de errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
